[terra-layout]Remove it
cerner/terra-framework pull request #1341
Opened 2020-12-04 06:05 UTC by saket2403

### Summary

Closes #

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

### Testing

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

2020-12-04 14:42 UTC, mjhenkes commented on packages/terra-layout/tests/wdio/layout-slide-panel-spec.js
>      browser.url('/#/raw/tests/terra-layout/layout/layout-slide-panel-example');
Remove the '#' please.

2020-12-07 06:21 UTC, saket2403 commented on packages/terra-layout/tests/wdio/layout-slide-panel-spec.js
>      browser.url('/#/raw/tests/terra-layout/layout/layout-slide-panel-example');
The build fails with a diff of 0.02 on travis only, on removing the `/#`.

2020-12-07 16:12 UTC, mjhenkes commented on packages/terra-layout/tests/wdio/layout-slide-panel-spec.js
>      browser.url('/#/raw/tests/terra-layout/layout/layout-slide-panel-example');
@saket2403 I'd like you to further investigate the cause. It's interesting that removing a redirect is causing a 0.02 diff on travis.

2020-12-07 16:13 UTC, mjhenkes requested changes
We should be able to remove the '/#' redirect.

2020-12-10 08:46 UTC, saket2403 commented
> We should be able to remove the '/#' redirect.

Updated wdio 44a238b. Got the screenshots to fail in local by adding FORM_FACTOR in package.json.

2020-12-10 15:01 UTC, mjhenkes approved these changes

2020-12-11 05:05 UTC, pranav300 approved these changes

2020-12-11 05:07 UTC, supreethmr approved these changes

2020-12-15 14:58 UTC, ryanthemanuel approved these changes

2020-12-15 15:00 UTC, merged