[terra-hookshot] Change Variable name to fix resize popup issue.
cerner/terra-framework pull request #1352
Opened 2021-01-12 06:29 UTC by saket2403

### Summary
Change Variable name to fix resize popup issue.
Closes #1344 

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

### Testing

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

2021-01-12 09:59 UTC, supreethmr commented on packages/terra-hookshot/CHANGELOG.md
> + * Change variable names overlooked in refactoring to fix resize popup issue
Formatting for change log heading seems to be missing here..!
```suggestion
### Fixed
* Fixed error thrown on resizing the popup due to incorrect variables name.
```

2021-01-12 14:43 UTC, supreethmr approved these changes

2021-01-12 15:12 UTC, dkasper-was-taken approved these changes

2021-01-12 15:30 UTC, StephenEsser approved these changes

2021-01-12 19:45 UTC, dkasper-was-taken commented
Might be worthwhile to add a jest test for this function if one isn't present.

2021-01-13 15:10 UTC, mjhenkes requested changes
Please add a jest test covering this case.

2021-01-19 13:44 UTC, pranav300 approved these changes

2021-01-21 05:46 UTC, saket2403 commented
Added jest 59c6d50

2021-01-21 15:20 UTC, mjhenkes approved these changes

2021-01-21 15:21 UTC, merged