[terra-menu] Set showHeader to false, display header for bounded
cerner/terra-framework pull request #1662
Opened 2023-05-31 05:02 UTC by sugan2416

### Summary

**What was changed:**

- Updated `showHeader` prop default value to false
- Allow header title to display when menu goes bounded

**Why it was changed:**

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-XXXX 

---

Thank you for contributing to Terra.
@cerner/terra

2023-06-02 05:49 UTC, ShettyAkarsh commented on packages/terra-menu/src/_MenuContent.jsx
> +    const isFullScreen = MenuUtils.isFullScreen(
is this checking only for bounded menu ?

2023-06-02 05:51 UTC, ShettyAkarsh commented
@sugan2416  will there be new scrensshots generated for bounded menu users ? as this changes will show the headers always going ahead for bounded menu ?

2023-06-16 16:58 UTC, sdadn requested changes
Can this be rebased with main so that it is up to date?

2023-06-16 16:58 UTC, sdadn commented on packages/terra-framework-docs/CHANGELOG.md
> +  * Updated example for `terra-menu`
```suggestion
  * Updated example for `terra-menu`.
```

2023-08-17 17:53 UTC, supreethmr commented
Closing this PR as the branch has become stale and PR does not have enough details about the issue OR Jira it's addressing. I would suggest to create new PR if required 
cc : @sugan2416

2023-08-17 17:53 UTC, closed without merging