[terra-collapsible-menu-view] Added multi select option in item group
cerner/terra-framework pull request #1775
Opened 2023-09-05 11:43 UTC by PK106552

### Summary

**What was changed:**
    Added support for multi select option in item group (terra-menu and terra-button-group).

**Why it was changed:**
    Previously item group was supporting only single select.

### Testing

This change was tested using:

- [x] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [x] Functional review

### Additional Details

**This PR resolves:**  UXPLATFORM-9535

UXPLATFORM-XXXX 

---

Thank you for contributing to Terra.
@cerner/terra

2023-09-11 18:08 UTC, supreethmr commented
when we try to select print message button collapisble-menu-view component crashes with below error message

<img width="1728" alt="Screenshot 2023-09-11 at 11 33 50 PM" src="https://github.com/cerner/terra-framework/assets/12869809/edc89566-49fd-49d9-832b-aa984fbfc81c">

2023-09-11 19:11 UTC, supreethmr commented
Not able to select the item when it is collapsed within menu and the on selection of menu item onChange is not triggered as shown in below recording.


https://github.com/cerner/terra-framework/assets/12869809/ece04a03-4b49-4e8e-927f-04693698b578


https://github.com/cerner/terra-framework/assets/12869809/80837b6b-af2c-4d67-92b3-b34e04b33c2c

2023-09-11 19:13 UTC, PK106552 commented
> when we try to select print message button collapisble-menu-view component crashes with below error message
> 
> <img alt="Screenshot 2023-09-11 at 11 33 50 PM" width="1728" src="https://user-images.githubusercontent.com/12869809/267108954-edc89566-49fd-49d9-832b-aa984fbfc81c.png">

Fixed

2023-09-14 14:51 UTC, sdadn requested changes

2023-09-14 14:51 UTC, sdadn commented on packages/terra-collapsible-menu-view/src/CollapsibleMenuViewItemGroup.jsx
> +import CollapsibleMenuView from '../lib/CollapsibleMenuView';
Why are we going importing from the lib folder? These are in the same folder so we can just do:

```suggestion
import CollapsibleMenuView from './CollapsibleMenuView';
```

2023-09-14 14:51 UTC, sdadn commented on packages/terra-collapsible-menu-view/src/CollapsibleMenuViewUtils.jsx
This needs a jest test file.

2023-09-14 15:15 UTC, PK106552 commented
We have created new PR for collapsible-menu-view so this PR is no longer required,

2023-09-14 15:16 UTC, closed without merging