[terra-date-time-picker] Fixes issue when time transition from DST to ST
cerner/terra-framework pull request #1792
Opened 2023-09-14 09:58 UTC by sugan2416

### Summary

**What was changed:**

Added check for valid datetime before calling time clarification modal

**Why it was changed:**

Datetime format method was called on null object.

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [x] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-9606 

---

Thank you for contributing to Terra.
@cerner/terra

2023-09-14 14:48 UTC, sdadn requested changes

2023-09-14 14:48 UTC, sdadn commented on packages/terra-date-time-picker/src/DateTimePicker.jsx
> +          {this.state.isAmbiguousTime && this.state.dateTime ? this.renderTimeClarification() : null}
How was this change tested?

2023-09-14 14:48 UTC, sdadn commented on packages/terra-date-time-picker/CHANGELOG.md
> +  * Fixed error when time transitions from DST to ST
What is the error? We should say what the error is.
```suggestion
  * Fixed error when time transitions from DST to ST.
```

2023-09-19 08:48 UTC, saket2403 approved these changes

2023-09-19 18:53 UTC, supreethmr approved these changes

2023-09-20 06:58 UTC, merged