Table column header tab index fix
cerner/terra-framework pull request #1883
Opened 2023-11-09 18:41 UTC by cm9361

### Summary

**What was changed:**
The Terra Table was updated such that the column headers will have a tab index on the button, if it exists, or else the table cell element.  Previously, the table cell for a grid context always had a tab index of -1.  The DataGrid component was also updated to properly account for this change.

**Why it was changed:**
The change was made because the cell having a tab index of -1 when a button was present caused the screen reader to read both element values.  This change resolved the accessibility issue.

### Testing

This change was tested using:

- [X] WDIO
- [X] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [X] Accessibility review
- [ ] Functional review

### Additional Details
N/A

**This PR resolves:**

UXPLATFORM-9804 

---

Thank you for contributing to Terra.
@cerner/terra

2023-11-09 20:01 UTC, kenk2 approved these changes

2023-11-09 20:03 UTC, cm9361 commented on packages/terra-table/src/subcomponents/ColumnHeaderCell.jsx
> +  const hasButtonElement = isSelectable && displayName;
I put it here so that the buttonTabIndex logic would be together in one block of code.

2023-11-09 21:25 UTC, eawww approved these changes

2023-11-13 14:21 UTC, sdadn approved these changes

2023-11-13 14:22 UTC, sdadn requested changes

2023-11-13 14:22 UTC, sdadn commented on packages/terra-table/CHANGELOG.md
> +  * Fixed tab index issues in the column header cells.
I believe this is in the wrong section after Friday's release

2023-11-13 15:21 UTC, sdadn approved these changes

2023-11-13 15:41 UTC, merged