[terra-application-links] add onTabClick optional property to terra-application-links interface
cerner/terra-framework pull request #2113
Opened 2024-04-01 13:25 UTC by sPavl0v

### Summary

Would like to add new property to provide an ability to add custom handler on link click.
**What was changed:**
Expose **onTabClick** property to a public interface of terra-application-links.
Change logic to trigger the callback when it's provided

**Why it was changed:**
There is a need to pass a callback function when link clicked

### Testing

This change was tested using:

- [ ] Jest

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-XXXX 

---

Thank you for contributing to Terra.
@cerner/terra

2024-04-03 20:04 UTC, kenk2 approved these changes

2024-04-03 20:46 UTC, sycombs requested changes

2024-04-03 20:46 UTC, sycombs commented on packages/terra-application-links/tests/jest/ApplicationTabs.test.jsx
> +  expect(wrapper).toMatchSnapshot();
Can we have a test that onTabClick is called when clicking the tab and avoid using snapshots? Here is an example: https://github.com/cerner/terra-framework/blob/7a086d9c163b297c985e420867a3042b870dec62/packages/terra-file-path/tests/jest/FilePath.test.jsx#L71

2024-04-03 20:46 UTC, sycombs commented on packages/terra-application-links/CHANGELOG.md
> +
minor nit:
```suggestion
* Added
  * Added `onTabClick` property to ApplicationLinks interface.

```

2024-04-11 14:40 UTC, sycombs approved these changes

2024-04-12 10:26 UTC, merged